version: "3.9"
services:
  postgres:
    restart: always
    image: postgres:latest
    environment:
    - PGUSER=postgres
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=flight
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  api:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
    - "8080:8080"
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
